on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
       - run: |
          sudo snap install terraform --classic
          ls
          pwd

       - run: |
          terraform init
          terraform plan
          terraform apply
