on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

       - run: |
          cd ..
          cd ..
          cd ..
          terraform init
          terraform plan
          terraform apply
